# Generated by Django 4.0.5 on 2022-06-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgethegapapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
