# Generated by Django 4.0.5 on 2022-06-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridgethegapapi', '0002_tutor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='session',
        ),
    ]
