# Generated by Django 4.0.5 on 2022-06-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgethegapapi', '0004_rename_session_review_review_tutor_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='tutors'),
        ),
    ]
