# Generated by Django 4.0.5 on 2022-06-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridgethegapapi', '0006_remove_session_parent_session_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='parent',
            new_name='parents',
        ),
    ]
