# Generated by Django 4.0.5 on 2022-06-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgethegapapi', '0007_rename_parent_session_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='language',
            field=models.ManyToManyField(related_name='languages', through='bridgethegapapi.SessionLanguage', to='bridgethegapapi.language'),
        ),
    ]
